### ISSUE TITLE
Can't install/start plugin

### ISSUE THREAD

**Issue by viorelhojda** [bpmn-io/camunda-transaction-boundaries#11]
__Description of the Bug__

After I installed the plugin (that is copy the extracted files and folder in the /resources/plugins directory from camunda modeler) when I start the Camunda Modeler I get this error:
INFO app:plugins loading /home/vio/tool/camunda-modeler-3.7.3-linux-x64/resources/plugins/camunda-modeler-autosave-plugin-master/index.js
INFO app:plugins loading /home/vio/tool/camunda-modeler-3.7.3-linux-x64/resources/plugins/camunda-transaction-boundaries-master/index.js
ERROR app:plugins failed to load /home/vio/tool/camunda-modeler-3.7.3-linux-x64/resources/plugins/camunda-transaction-boundaries-master/index.js /home/vio/tool/camunda-modeler-3.7.3-linux-x64/resources/plugins/camunda-transaction-boundaries-master/lib/index.js:1
import TransactionBoundaries from './TransactionBoundaries';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:815:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/vio/tool/camunda-modeler-3.7.3-linux-x64/resources/plugins/camunda-transaction-boundaries-master/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)

__Steps to Reproduce__

1. install Camunda Modeler latest version 3.7.3
2. install camunda-transaction-boundaries plugin from https://github.com/bpmn-io/camunda-transaction-boundaries
3. start the Camunda Modeler

__Expected Behavior__

I expect the camunda Modeler to start.

__Environment__

- Host (Browse Chrome  81.0.4044.138/Node 9.11.1)
- OS: Ubuntu  81.0.4044.138
- Library version: 

Sorry for the triviality of the bug :(

**Comment by pinussilvestrus** [comment]
Hi @viorelhojda,

please see the note inside the Readme of the project you have linked. It says you find the actual Camunda Modeler plugin [here](https://github.com/camunda/camunda-modeler-plugins/tree/master/camunda-transaction-boundaries-plugin). That should work fine.

The other one you mentioned is just the [`bpmn-js`](https://github.com/bpmn-io/bpmn-js) extension. 

Feel free to re-open if something is not working.
