### ISSUE TITLE
Plugin crashes during start of Camunda modeler 1.16.2

### ISSUE THREAD

**Issue by doerfli** [bpmn-io/camunda-transaction-boundaries#2]
When the plugin is being used with the latest version of the Camunda modeler (1.16.2), the the camunda modeler crashes on startup with this exception 

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'lodash/collection/forEach'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/opt/adcubum/devenv/camunda-modeler-1.16.2/camunda-modeler/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/adcubum/devenv/camunda-modeler-1.16.2/camunda-modeler/plugins/bpmn-js-transaction-boundaries-master/lib/TransactionBoundaries.js:3:15)
    at Object.<anonymous> (/opt/adcubum/devenv/camunda-modeler-1.16.2/camunda-modeler/plugins/bpmn-js-transaction-boundaries-master/lib/TransactionBoundaries.js:253:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

**Comment by nikku** [comment]
Closed as outdated.

The plugin works (with the latest version) against Camunda Modeler 2.2+.
