### ISSUE TITLE
Camunda modeler 2.2.4 won't start with camunda-transaction-boundaries 1.0.1

### ISSUE THREAD

**Issue by doerfli** [bpmn-io/camunda-transaction-boundaries#6]
When starting camunda-modeler 2.2.4 with version 1.0.1 of camunda-transaction-boundaries plugin, the modeler won't start. The following exception is thrown

```
Uncaught Exception:
/Users/myuser/Library/Application Support/camunda-modeler/plugins/camunda-transaction-boundaries/lib/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import TransactionBoundaries from './TransactionBoundaries';
                                                                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:678:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by nikku** [comment]
We need to reproduce this and see what's going on.

It's not a nice behavior to prevent the modeler from starting.

**Comment by nikku** [comment]
Cannot reproduce this. I guess you confused this library with the actual [Camunda Modeler plug-in](https://github.com/camunda/camunda-modeler-plugins/tree/master/camunda-transaction-boundaries-plugin).

I added a hint to the README, explaining that this is not the actual plug-in.

**Comment by doerfli** [comment]
You are right, i confused that. Thanks for the hint!
